# Generated by Django 5.2.4 on 2025-07-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Главное изображение')),
                ('news', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Новостное изображение')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Галерея изображений')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
