# Generated by Django 5.2.4 on 2025-07-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_image_alter_news_views_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='news',
            name='gallery_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Галерея изображений'),
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Новостное изображение'),
        ),
    ]
