# Generated by Django 5.2.4 on 2025-07-25 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_image_news_gallery_image_news_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
